[dependencies]
base = "0.13.0"
map9 = "https://github.com/ZhenyaUsenko/motoko-hash-map#v9.0.1@10b68f6ea8df5e72dfa4c07a50c8bb60a916c233"
vector = "0.4.1"
star = "0.1.1"
account = "1.0.1"
icrc3-mo = "0.2.6"
icrc10-mo = "0.0.1"
xtended-random = "1.0.0"
icrc75-mo = "0.1.1"
ic-certification = "0.1.3"
timer-tool = "0.0.3"
ovs-fixed = "0.1.2"
candy = "0.3.0"
icrc1-mo = "0.0.15"
stableheapbtreemap = "1.5.0"
icrc104-mo = "0.0.1"

[dev-dependencies]
test = "2.0.0"
fuzz = "0.2.1"

[package]
name = "af-role-rotator"
version = "0.0.1"
description = "Role Rotator based on ICRC-75 and ICRC-104"
repository = "https://github.com/icdevsorg/af-role-rotator"
keywords = [ "icrc75", "icrc104", "roles", "governance", "sns" ]
